apiVersion: apps/v1
kind: Deployment
metadata:
  name: testjava
  namespace: sagethram-dev
spec:
  template:
    spec:
      containers:
      - name: dapo-reference-cd-pipeline    
        image: image-registry.openshift-image-registry.svc:5000/sagethram-dev/new-pipeline-9j9vr3:latest
